### ISSUE TITLE
timeline-ui

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/kk-website#30]
**Tasks - High Priority**
- [x] support preview-images on the timeline-page
- [x] highlight the date of the event in the full article
   - distinguish the date of the event from the display of the articles author (currently one could assume that the event-date is the date where the article was published)
- [ ] support different types of events and distinguish them visually:
   - with articles
   - without articles (only title)
   - "special events" (e.g. first Bitcoin block mined)
- [ ] implement a navigation/scrollbar for events

**Tasks - Low Priority**
- [ ] provide a way to categorize timeline-articles
   -  e.g. "Bitcoin", "Scandal", "Hack", "Publication", "Scam", "ICO", ...
- [ ] provide a way to filter timeline-articles in the main-overview by category
- [ ] provide a navigation in the main-article (back, forward)

**Comment by marc0olo** [comment]
@the-icarus here we already have the open task regarding tbe different types of events. just as reminder after our discussion today

**Comment by marc0olo** [comment]
additionally it would be nice to have a permalink for specific timeline-entries if possible and not too much work.

**Comment by the-icarus** [comment]
@marc0olo See #70 It contains some of the above mentioned tasks.

**Comment by marc0olo** [comment]
we want to change the design for the moment to look as follows:
<img width="1260" alt="Bildschirmfoto 2020-01-31 um 14 28 19" src="https://user-images.githubusercontent.com/8124114/73542906-0c175580-4436-11ea-963f-e5b524512ea6.png">
