### ISSUE TITLE
lexicon-ui

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/kk-website#32]
**Tasks**
- [x] provide a way to contribute lexicon entries and respective entry-descriptions
   - to be discussed: YAML vs. Markdown
- [x] implement a page that displays all lexicon-entries
- [x] implement a lexicon navigation (A-Z)

**Comment by marc0olo** [comment]
@the-icarus I created a branch for the issue that already includes content for the lexicon

**Comment by the-icarus** [comment]
@marc0olo I think this one should be resolved with PR #52

**Comment by marc0olo** [comment]
yes, #52 closes this issue
