### ISSUE TITLE
frontpage/landingpage-ui

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/kk-website#33]
**Tasks**
- [ ] adjust the project-section
   - [ ] add teaser with slider and project-image (æternity, Arkane, ...)
   - [ ] add "tech / frameworks" to the project-teaser and display that (e.g. "Java", "Python", "Unity, ...)
      - to be discussed: should we skip that and keep it in the "tags"-attributes of the project?
- [ ] krautMISSION-section that describes the goals and the vision of kryptokrauts
   - content will be delivered by @mitch-lbw and @marc0olo 
- [x] "fix" the display of the teamMember-component
    - see Andreas Müller
- [ ] change the order of the sections as follows:
    1. projects
    1. mission
    1. team
